# Generated by Django 5.1.6 on 2025-02-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pagina', '0002_alter_cliente_celular_alter_cliente_coordenadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tipo',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('Mesa', 'Mesa'), ('A recoger', 'A recoger')], default=2, max_length=100),
        ),
    ]
