# Generated by Django 5.1.6 on 2025-02-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pagina', '0003_alter_ticket_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tipo',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('Mesa', 'Mesa'), ('Recoger', 'Recoger')], default=2, max_length=100),
        ),
    ]
